/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  ipWhitelist: [],
  modules: [
    {
      module: 'alert',
      config: {}
    },
    {
      module: 'MMM-Remote-Control',
      config: {}
    },
    {
      module: 'MMM-Remote-Control-Repository',
      config: {}
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {},
      header: ''
    },
/*    {
      module: 'MMM-MQTT',
      position: 'bottom_left',
      header: 'MQTT',
      config: {
        logging: false,
        mqttServers: [
          {
            address: 'openhab.maggo.lan',
            port: '1883',
            subscriptions: [
              {
                topic: '/hmip/3014F711A00010D8A990A2FF/actualTemperature',
                label: 'Outside',
                suffix: '°C',
                decimals: 1,
                sortOrder: 10,
                maxAgeSeconds: 360,
                colors: [
                  {
                    upTo: 0,
                    value: 'blue',
                    label: 'blue',
                    suffix: 'blue'
                  },
                  {
                    upTo: 10,
                    value: '#00ccff',
                    label: '#00ccff',
                    suffix: '#00ccff'
                  },
                  {
                    upTo: 15,
                    value: 'yellow'
                  },
                  {
                    upTo: 25,
                    label: 'green',
                    suffix: 'green'
                  },
                  {
                    upTo: 30,
                    label: 'red'
                  }
                ]
              },
              {
                topic: '/hmip/3014F711A0000E9A498BAE8A/actualTemperature',
                label: 'Wohnzimmer',
                suffix: '°C',
                decimals: 1,
                sortOrder: 20,
                maxAgeSeconds: 354
              },
              {
                maxAgeSeconds: '30',
                topic: '/hmip/3014F711A0001558A99D670F/windowState',
                label: 'Balkontür',
                sortOrder: 100,
                conversions: [
                  {
                    from: 'OPEN',
                    to: 'offen'
                  },
                  {
                    from: 'CLOSED',
                    to: 'zu'
                  }
                ]
              }
            ]
          }
        ]
      }
    },
*/
    {
      module: 'clock',
      position: 'top_left',
      header: '',
      config: {
        timezone: 'Europe/Vienna',
        lat: 47.262691,
        lon: 11.394700,
        clockBold: false,
        showSunTimes: true,
        showMoonTimes: true
      }
    },
    {
      module: 'calendar',
      position: 'top_left',
      config: {
        maximumNumberOfDays: '10',
        timeFormat: 'absolute',
        nextDaysRelative: 'true',
        calendars: [
          {
            symbol: 'male',
	    maximumNumberOfDays: '8',
            url: 'https://calendar.google.com/calendar/ical/m.waldegger%40gmail.com/private-1ece4391adaa100bf361f6f51855842b/basic.ics'
          },
          {
            symbol: 'briefcase',
            name: 'synedra MWa',
            maximumNumberOfDays: '5',
            maximumEntries: '10',
            url: 'https://calendar.google.com/calendar/ical/m.waldegger%40synedra.com/private-565f062b5d858ad0394797eb125331da/basic.ics'
          },
          {
            symbol: 'heapositionrt',
	    maximumNumberOfDays: '14',
            url: 'https://calendar.google.com/calendar/ical/mru4au307chi0ergmdars1ta3k%40group.calendar.google.com/private-5c343277363954dd9813a3f449b78e53/basic.ics'
          }
        ],
        excludedEvents: [
          {
            filterBy: 'StandUp',
            caseSensitive: false
          }
        ]
      },
      header: ''
    },
        {
                module: 'MMM-Todoist',
                position: 'bottom_left',   // This can be any of the regions. Best results in left or right regions.
                header: 'Einkaufsliste', // This is optional
                config: { // See 'Configuration options' for more information.
                        hideWhenEmpty: true,
                        accessToken: 'afa4238998543c806aab45ff6eb5137c594db1af',
                        maximumEntries: 15,
                        updateInterval: 10*60*1000, // Update every 10 minutes
                        fade: true,
                        fadePoint: 0.1,
                        showProject: false,
                        // projects and/or labels is mandatory:
                        projects: [ 2284606861 ],
                        labels: [ "Alexa"]
      }
        },

    {
      module: 'compliments',
      position: 'middle_center',
      header: '',
      config: {
	remoteFile: "https://gist.githubusercontent.com/E3V3A/ead2c26afff44ab57220c912239fcce4/raw/be1dee8f805a433f6ee0fa3556d1927da14e7799/compliments.json",
        compliments: {
          anytime: [
            'Hey there sexy!',
	    'Come sei dolce!'
          ],
          morning: [
            'Good morning, handsome!',
            'Enjoy your day!',
	    'On a scale from 1 to 10, you’re an 11',	
            'How was your sleep?'
          ],
          afternoon: [
            'Hello, beauty!',
            'You look sexy!',
            'Looking good today!'
          ],
          evening: [
            'Wow, you look hot!',
            'You look nice!',
            'Hi, sexy!'
          ],
          day_sunny: [
            'Today is a sunny day',
            "It's a beautiful day"
          ],
          snow: [
            'Snowball battle!'
          ],
          rain: [
            "Don't forget your umbrella"
          ],
          '....-01-01': [
            'Happy new year!'
          ]
        }
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: '',
      config: {
        type: "current",
        location: "Innsbruck, AT",
        apiKey: "80dd89bbe85519f11399f10d0ca3bdbf"
      }
    },
    {
      module: 'weather',
      position: 'top_right',
      header: '',
      config: {
        weatherProvider: 'openweathermap',
        type: 'forecast',
        location: 'Innsbruck',
        locationID: '2775220',
        apiKey: '80dd89bbe85519f11399f10d0ca3bdbf',
        maxNumberOfDays: 4,
        showRainAmount: true
      }
    },
    {
      module: 'MMM-cryptocurrency',
      position: 'bottom_right',
      header: '',
      config: {
        apikey: '68b538ca-41aa-405b-bdc4-e56495b7d1e9',
        currency: [
          'bitcoin',
  	  'ethereum',
          'bitcoin-cash',
	  'xrp'
        ],
        conversion: 'EUR',
        displayType: 'logo',
        showGraphs: true,
        significantDigits: [
          1
        ],
        fontSize: 'small'
      }
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      header: '',
      config: {
        feeds: [
          {
            title: 'Standard.at',
            url: 'http://derStandard.at/?page=rss&ressort=Seite1'
          },
          {
            title: 'TT',
            url: 'https://www.tt.com/rss/news.xml'
          }
        ],
        reloadInterval: 600000
      }
    }
  ]
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
